# Generated by Django 3.1.3 on 2021-03-06 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличное'), ('enumeration', 'Перечисление')], max_length=250, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(choices=[('D', 'Доллар'), ('S', 'Сум')], max_length=250, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
