# Generated by Django 3.1.3 on 2021-03-09 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counter_party', '0003_auto_20210309_0918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_auto_20210309_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(verbose_name='Цена')),
                ('payment_type', models.CharField(choices=[('S', 'Сум'), ('D', 'Доллар')], max_length=250, verbose_name='Тип оплаты')),
                ('type', models.CharField(choices=[('Outcome', 'Превзойти'), ('Income', 'Доход')], max_length=250, verbose_name='Тип журнала платежей')),
                ('counter_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter_party.counterparty', verbose_name='Контрагент')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='Доставка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал платежей',
                'verbose_name_plural': 'Журналы платежей',
            },
        ),
    ]
