# Generated by Django 3.1.3 on 2021-03-12 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_auto_20210310_0951'),
        ('counter_party', '0007_remove_counterparty_balance_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(verbose_name='Цена')),
                ('pay_type', models.CharField(choices=[('Income', 'Доход'), ('Outcome', 'Расходы')], max_length=250, verbose_name='Тип журнала платежей')),
                ('counter_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter_party.counterparty', verbose_name='Контрагент')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='Доставка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал платежей',
                'verbose_name_plural': 'Журналы платежей',
            },
        ),
    ]
