# Generated by Django 3.1.3 on 2021-03-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210309_1143'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('D', 'Доллар'), ('S', 'Сум')], max_length=250, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Income', 'Доход'), ('Outcome', 'Расходы')], max_length=250, verbose_name='Тип журнала платежей'),
        ),
    ]
