# Generated by Django 3.1.3 on 2021-03-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210309_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='pay_type',
        ),
    ]
