# Generated by Django 3.1.3 on 2021-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210309_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('Outcome', 'Расходы'), ('Income', 'Доход')], max_length=250, verbose_name='Тип журнала платежей'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('S', 'Сум'), ('D', 'Доллар')], max_length=250, verbose_name='Тип оплаты'),
        ),
    ]
