# Generated by Django 3.1.3 on 2021-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210310_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('Outcome', 'Расходы'), ('Income', 'Доход')], max_length=250, verbose_name='Тип журнала платежей'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('D', 'Доллар'), ('S', 'Сум')], max_length=250, verbose_name='Тип оплаты'),
        ),
    ]
