# Generated by Django 3.1.3 on 2021-03-06 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter_party_character', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter_Party_Character',
            new_name='CounterPartyCharacter',
        ),
    ]
