# Generated by Django 3.1.3 on 2021-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('status', models.CharField(choices=[('not active', 'не активен'), ('active', 'активен')], max_length=250, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставкаы',
            },
        ),
    ]
