# Generated by Django 3.1.3 on 2021-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('active', 'активен'), ('not active', 'не активен')], max_length=250, verbose_name='Статус'),
        ),
    ]
