# Generated by Django 3.1.3 on 2021-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210309_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('active', 'активен'), ('not active', 'не активен')], max_length=250, verbose_name='Статус'),
        ),
    ]
