# Generated by Django 3.1.3 on 2021-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('balance_usd', models.FloatField(default=0, verbose_name='USD')),
                ('balance_uzs', models.FloatField(default=0, verbose_name='UZS')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('not active', 'не активен'), ('active', 'активен')], max_length=250, verbose_name='Статус')),
                ('organization', models.CharField(blank=True, max_length=250, null=True, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Второй телефон')),
            ],
            options={
                'verbose_name': 'Контр агент',
                'verbose_name_plural': 'Контр агенты',
            },
        ),
    ]
