# Generated by Django 3.1.3 on 2021-03-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0002_auto_20210306_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='status',
            field=models.CharField(choices=[('not active', 'не активен'), ('active', 'активен')], max_length=250, verbose_name='Статус'),
        ),
    ]
