# Generated by Django 3.1.3 on 2021-03-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter_party', '0006_auto_20210310_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='balance_usd',
        ),
    ]
